export const LOAD_RESTAURANTS_SUCCESS = 'LOAD_RESTAURANTS_SUCCESS';
export const RELOAD_RESTAURANTS_SUCCESS = 'RELOAD_RESTAURANTS_SUCCESS' // when city or category changes we should reload
export const LOAD_CITIES_SUCCESS = 'LOAD_CITIES_SUCCESS';
export const CITY_SELECTION_SUCCESS = 'CITY_SELECTION_SUCCESS';
export const CATEGORY_SELECTION_SUCCESS = 'CATEGORY_SELECTION_SUCCESS';